name: ci

on:
  push:
    branches:
      - 'master'

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       # ...
#       -
#         name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           load: true
#           push: true
#           tags: shirzadi/ehsan:latest,shirzadi/ehsan:${{ env.GITHUB_SHA }}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: shirzadi/ehsan:latest
      -
        name: Push it!
        #run: docker push ${{ env.IMAGE }}:${{ env.GIT_SHA }}
        run: docker push shirzadi/ehsan:latest
